!FINDING A BIG NUMBER FROM A GIVEN SET OF ARRAY

PROGRAM BIG_PICKER
 IMPLICIT NONE
 INTEGER::I,J,N
 REAL::NOS(1000),BIG=0
 PRINT*,"ENTER HOW MANY DATA YOU HAVE"
 READ*,N
 PRINT*,"NOW ENTER THE NUMBERS TO FINDING BIG NO"
 DO I=1,N
  READ*,NOS(I)
  IF (NOS(I) > BIG) THEN
    BIG= NOS(I)
  ENDIF
 END DO
 PRINT*,"BIG NO=",BIG
 END PROGRAM BIG_PICKER
